{% set name = "rosco" %}
{% set version = "2.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

# source:
#   url: https://github.com/openfast/openfast/archive/v{{ version }}.tar.gz
#   sha256: 2b368e8c8211ebed03e87fb3e89ef733b7e4be4848834da4034f8419d618446c
#   # Download the tar-ball and do `openssl sha256 file.tar.gz` to update

source:
  git_url: https://github.com/NREL/ROSCO.git
  git_rev: v{{ version }}
  # git_depth: 1 # (Defaults to -1/not shallow)

build:
  number: 0
  skip: False  # [win]

requirements:
  build:
    - {{ compiler('fortran') }}       # [unix]
    - {{ compiler('m2w64_fortran') }}  # [win]
    - make
    - cmake
  host:
    - m2w64-toolchain # [win]
    - libblas
    - liblapack
    - libpython # [win]

# test:
#   commands:
#     - openfast -h

about:
  home: https://github.com/NREL/rosco
  license: Apache-2.0
  license_file: LICENSE
  summary: Reference OpenSource Wind Turbine Controller
  description: NREL-developed wind turbine controller for bladed-style communications
  # doc_url: http://openfast.readthedocs.io
  dev_url: https://github.com/NREL/rosco

extra:
  recipe-maintainers:
    - nikhar-abbas