# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# /Users/nabbas/Documents/WindEnergyToolbox/conda-recipes/ROSCO-recipe, last modified Wed Jul  1 12:53:52 2020
# ------------------------------------------------

package:
    name: rosco
    version: 2.0.1
source:
    git_rev: v2.0.1
    git_url: https://github.com/NREL/ROSCO.git
build:
    number: '0'
    string: h12d9a10_0
requirements:
    build:
        - bzip2 1.0.8 h0b31af3_2
        - ca-certificates 2020.6.20 hecda079_0
        - cctools 927.0.2 h5ba7a2e_4
        - clang 9.0.1 default_hf57f61e_0
        - clang-tools 9.0.1 default_hf57f61e_0
        - clang_osx-64 9.0.1 h05bbb7f_2
        - clangxx 9.0.1 default_hf57f61e_0
        - clangxx_osx-64 9.0.1 h05bbb7f_2
        - cmake 3.17.0 hd28f656_0
        - compiler-rt 9.0.1 h6a512c6_3
        - compiler-rt_osx-64 9.0.1 h99342c6_3
        - expat 2.2.9 h4a8c4bd_2
        - gfortran_impl_osx-64 7.3.0 hf4212f2_2
        - gfortran_osx-64 7.3.0 h22b1bf0_11
        - gmp 6.2.0 h4a8c4bd_2
        - isl 0.19 0
        - krb5 1.17.1 h14dd6a4_1
        - ld64 450.3 h3c32e8a_4
        - libcurl 7.71.0 he6690cf_0
        - libcxx 10.0.0 h1af66ff_2
        - libedit 3.1.20191231 hed1e85f_0
        - libgfortran 4.0.0 0
        - libiconv 1.15 h0b31af3_1006
        - libllvm9 9.0.1 h7475705_1
        - libssh2 1.9.0 h39bdce6_2
        - libuv 1.38.0 h0b31af3_0
        - llvm-tools 9.0.1 h1341992_1
        - llvmdev 9.0.1 h7475705_1
        - make 4.3 h0b31af3_0
        - mpc 1.1.0 h4160ff4_1007
        - mpfr 4.0.2 h65ac59c_1
        - ncurses 6.1 h0a44026_1002
        - openssl 1.1.1g h0b31af3_0
        - rhash 1.3.6 h1de35cc_1001
        - tapi 1000.10.8 ha1b3eb9_4
        - tk 8.6.10 hbbe82c9_0
        - xz 5.2.5 h0b31af3_0
        - zlib 1.2.11 h0b31af3_1006
    host:
        - libblas 3.8.0 17_openblas
        - libcxx 10.0.0 h1af66ff_2
        - libgfortran 4.0.0 2
        - liblapack 3.8.0 17_openblas
        - libopenblas 0.3.10 h3d69b6c_0
        - llvm-openmp 10.0.0 h28b9765_0
    run:
        - libblas >=3.8.0,<4.0a0
        - libcxx >=9.0.1
        - libgfortran >=4.0.0,<5.0.0.a0
        - liblapack >=3.8.0,<3.9.0a0
about:
    description: NREL-developed wind turbine controller for bladed-style communications
    dev_url: https://github.com/NREL/rosco
    home: https://github.com/NREL/rosco
    license: Apache-2.0
    license_file: LICENSE
    summary: Reference OpenSource Wind Turbine Controller
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - nikhar-abbas
